# Generated by Django 2.2.6 on 2021-07-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tilte',
            new_name='title',
        ),
    ]
