# Generated by Django 2.2.6 on 2021-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0004_auto_20210713_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
