# Generated by Django 2.2.6 on 2021-07-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0005_auto_20210720_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
    ]
