# Generated by Django 2.2.6 on 2021-07-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0002_auto_20210717_1513'),
        ('yamdb', '0005_auto_20210716_1057'),
    ]

    operations = [
    ]
