# Generated by Django 2.2.6 on 2021-07-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0006_merge_20210717_2305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
    ]
