# Generated by Django 2.2.6 on 2021-07-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0008_auto_20210718_1309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
    ]
