# Generated by Django 2.2.6 on 2021-07-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0009_auto_20210718_1341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
