# Generated by Django 2.2.6 on 2021-07-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0010_auto_20210718_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
    ]
