# Generated by Django 2.2.6 on 2021-07-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0011_auto_20210718_1656'),
        ('yamdb', '0010_auto_20210718_1321'),
    ]

    operations = [
    ]
